---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/main.yml"
  tags:
    - packetbeat

- name: configure elastic repo
  include_role:
    name: nephelaiio.elastic_repo
  when: packetbeat_repo_manage | bool


- block:

    - name: install yum version lock support
      package:
        name: yum-plugin-versionlock
      when: ansible_os_family == 'RedHat'

    - name: disable yum package lock
      command: "yum versionlock delete {{ item }}"
      ignore_errors: yes
      loop: "{{ [packetbeat_packages] | flatten }}"
      when: ansible_os_family == 'RedHat'
      tags:
        - skip_ansible_lint

    - name: disable apt package lock
      command: "apt-mark unhold {{ item }}"
      loop: "{{ [packetbeat_packages] | flatten }}"
      when: ansible_os_family == 'Debian'

  when: packetbeat_package_hold | bool
  ignore_errors: yes

- name: install packetbeat elastic packages
  package:
    name: "{{ packetbeat_packages | default(packetbeat_package_names_els) }}"
    state: "{{ packetbeat_package_state }}"

- block:

    - name: enable apt package hold
      command: "apt-mark hold {{ item }}"
      loop: "{{ [packetbeat_packages] | flatten }}"
      when:
        - ansible_os_family == 'Debian'

    - name: enable yum package lock
      command: "yum versionlock add {{ item }}"
      loop: "{{ [packetbeat_packages] | flatten }}"
      when:
        - ansible_os_family == 'RedHat'
      tags:
        - skip_ansible_lint

  when: packetbeat_package_hold | bool

- name: configure packetbeat
  copy:
    content: |
      # Ansible managed

      {{ packetbeat_conf | to_nice_yaml(indent=2) }}
    dest: "{{ packetbeat_conf_path }}"
  notify: restart packetbeat
  when:
    - packetbeat_conf is defined
    - packetbeat_conf_manage | bool

- name: manage packetbeat services
  service:
    name: "{{ packetbeat_service_name }}"
    state: "{{ packetbeat_service_status }}"
    enabled: "{{ packetbeat_service_enabled }}"
