---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
    privileged: yes
    command: /usr/sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: xenial
    image: ubuntu:xenial
    privileged: yes
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: bionic
    image: ubuntu:bionic
    privileged: yes
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: stretch
    image: debian:stretch
    privileged: yes
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    vars:
      packetbeat_conf:
        packetbeat:
          monitors:
            - type: http
              schedule: '*/1 * * * * * *'
              urls:
                - https://www.google.com
          output:
            elasticsearch:
              hosts:
                - "localhost:9200"
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
